#!/bin/bash
set -euxo pipefail

# Cluster was created by the track setup-server; just confirm it is reachable.
kubectl wait --for=condition=Ready nodes --all --timeout=120s

echo "Challenge 1 setup complete"
